---
layout: archive
title: Lean Prover Zulip Chat Archive
permalink: archive/113488general/39459wellfoundnessinthekernel.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/113488general/index.html">general</a>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/113488general/39459wellfoundnessinthekernel.html">well foundness in the kernel</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com">

{% raw %}
<a name="171166383"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/well%20foundness%20in%20the%20kernel/near/171166383" class="zl"><img src="https://leanprover-community.github.io/assets/img/zulip2.png" alt="view this post on Zulip"></a> <a href="https://leanprover-community.github.io/archive/113488general/39459wellfoundnessinthekernel.html#171166383">Paul-Nicolas Madelaine (Jul 18 2019 at 12:52)</a>:</h4>
<p>Hi everyone,</p>
<p>I'm running in some issues with well foundness. I defined a function using the using_well_founded key word and a well founded relation that I defined.<br>
My function is running fine in the VM, but it seems like the kernel is not computing the function at all, for instance when I'm applying reflexivity.<br>
I don't even get a timeout, the elaborator just fails immediatly.</p>
<p>Did anyone encountered similar issues with well foundness blocking computation in the kernel?</p>


{% endraw %}

{% include archive_update.html %}